name: "My first workflow"

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs: 
  test:
    runs-on: windows-latest
    steps:
      - name: "Say hello"
        run: echo "Hello from GitHub Actions 🙌"